---
services:
  fastapi:
    container_name: fastapi
    # depends_on:
    #   - mysql
    environment:
      TZ: America/New_York
    hostname: fastapi-app
    image: smith8ca/fastapi-container-app:latest
    labels:
      - homepage.group=Local Services
      - homepage.name=FastAPI
      - homepage.icon=
      - homepage.href=${HOST}:${PORT}
      - homepage.description=FastAPI application
    ports:
      - ${PORT}:443
    restart: unless-stopped
    volumes:
      - fastapi-app:/data

volumes:
  fastapi-app: null
